parameters:

services:
    # Listener pour la création d'historique à chaque création d'alerte
    App\EventListener\AlerteCreationListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist, entity: App\Entity\Alerte }

    # Configuration par défaut des services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services (listeners, commandes, etc.)

    # Inclusion des classes dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
